# Generated by Django 3.1.7 on 2021-03-08 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
